apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-distroless
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-distroless
subjects:
  - kind: ServiceAccount
    name: example-distroless
    namespace: default