apiVersion: v1
kind: Service
metadata:
    name: example-distroless
    namespace: default
    labels:
        app: example-distroless
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
          targetPort: 8080
    selector:
        app: example-distroless
